### ISSUE TITLE
Unreal Engine 5 + DX12

### ISSUE THREAD

**Issue by VR-Punk** [TheNewJavaman/unreal-vr#31]
your support of Unreal Engine 4 in DX11 is superfluous, there are vorpx and nvidia 3dvision (Helixvision) which support that, already ! 

we don't need a battle between vorpx and r.e.a.l.vr, who released mods for the same games instead of different games. And we don't need a battle in the UE4 DX11 support !

Why not Unreal Engine 5 + DX12 ?

**Comment by TheNewJavaman** [comment]
I understand, but there many reasons why this mod will be a better alternative:

- Vorpx doesn't work properly for many games; most are not stereoscopic, only flatscreen in VR
- Nvidia 3DVision is not supported on AMD or RTX 3000-series cards
- Vorpx and 3DVision do not support proper 6dof head tracking
- RealVR only supports a few games, none of which are UE4
- Very few VR mods exists for most UE4 games, since the vast majority are not compiled with VR support

Besides, I'm just having fun creating a ***free*** mod :) This isn't about satisfying paying customers, since there aren't any!

Regardless, I am already working on UE5 and DX12 support, so stay tuned for that in the next few months.
